server:
  port: 8010
spring:
  application:
    name: microservice-simple-consumer-movie
eureka:
   client:
     serviceUrl:
       defaultZone: http://localhost:8761/eureka/ 
   instance:
     prefer-ip-address: true
#feign:
#  hystrix:
#    enable: false
hystrix:
  command:
    default:
       execution:
         #isolation:
           #thread:
             #timeoutInMilliseconds: 5000
          timeout:
            enabled: false
