server:
  port: 8010
spring:
  application:
    name: microservice-simple-consumer-movie
eureka:
   client:
     serviceUrl:
       defaultZone: http://localhost:8761/eureka/ 
   instance:
     prefer-ip-address: true
# 解决超时异常问题
#feign:
#  hystrix:
#    enable: false
hystrix:
  command:
    default:
       execution:
         #isolation:
           #thread:
             #timeoutInMilliseconds: 5000
          timeout:
            enabled: false
 # 使用属性自定义Feign配置
 #feign:
 #  client:
 #  # 属性配置比Java代码配置的方式优先级更高，如果想要反之，可进行如下配置
 #    default-to-properties=false
 #   config:
 #     feignName/default:
 #      # 相当于Request.Options
 #       connectTimeout: 5000
 #       # 相当于Request.Options
 #       readTimeout: 5000
 #       # 配置Feign的日志级别，相当于代码配置方式中的Logger
 #       loggerLevel: full/basic
 #       # Feign的错误解码器，相当于代码配置方式中的ErrorDecoder
 #       errorDecoder: com.example.SimpleErrorDecoder
 #       # 配置重试，相当于代码配置方式中的Retryer
 #       retryer: com.example.SimpleRetryer
 #       # 配置拦截器，相当于代码配置方式中的RequestInterceptor
 #       requestInterceptors:
 #         - com.example.FooRequestInterceptor
 #         - com.example.BarRequestInterceptor
 #       decode404: false
        
        