spring:
  application:
    name: microservice-discovery-eureka-ha
eureka: 
   client: 
     serviceUrl:
       defaultZone: http://peer2:8762/eureka/,http://peer1:8761/eureka/
---
spring:
  # 指定profile=peer1
  profiles: peer1
server:
  port: 8761 
eureka:
  instance:
    # 指定当profile=peer1时，主机名是peer1
    hostname: peer1
---
spring:
  profiles: peer2
server:
  port: 8762
eureka:
  instance:
    hostname: peer2
    
    