server:
  port: 8761
eureka:
  client:
    registerWithEureka: false #是否将自己注册到Eureka Server，默认为true，当前应用就是Eureka Server所以设为false
    fetchRegistry: false #是否从Eureka获取注册信息，默认为true，单点Eureka Server，不需要同步其他的Eureka Server节点的数据，故而设为false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址，多个地址间可用，分隔
    
    enableSelfPreservation: false
    